# ECE324 Assignment 1 Part 1

## Tasks

- [x] Load `matrix.csv` file into a NumPy array called `matrix` using `numpy.loadtxt`.
- [x] Load `vector.npy` -> `vector` using `numpy.load`.
- [x] Perform `output = matrix x vector` using loops to iterate through columns and rows.
    - [x] Save output variable to `output_forloop.csv` using `numpy.savetxt`.
- [x] Perform `output = matrix x vector` using NumPy's `numpy.dot`.
    - [x] Save as `output_dot.npy` using `numpy.save`
- [x] Compute difference between `output` and `output_2`, save it to CSV called `output_difference.csv`.
- [x] Answer the __question__ below.

## Question

_Question: IF the two files you compared above are the same, does it prove that your code is correct? Explain._

_Answer:_ Strong similarity give a good hint that the code is *probably* correct, but it by no means proves it. I may, for instance, have made a mistake in the way was assigning values during my computation resulting in the copying of a an incorrect result to both files. As well, the files are saved differently (CSV vs. npy) -- depending on what 'comparison' and 'the same' mean, I may arrive at an incorrect conclusion. If I were to examine the contents of the files in an intelligent fashion and take into account the fact that the floating point arithmetic may result in slightly different results, then I could get a decent sense of the correctness. At no point, however, would I be able to 'prove' the correctness of my code through any observation of the output.

In [43]:
##############
# Import Box #
##############

import numpy as np

In [44]:
################
# Loading Data #
################

matrix = np.loadtxt('../Resources/matrix.csv', delimiter=',')
vector = np.load('../Resources/vector.npy')

print(vector)
matrix

[[10]
 [20]
 [15]]


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [45]:
#################################
# Manual Looping Implementation #
#################################

output = np.zeros( (len(vector), 1) )

for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        output[i][0] += matrix[i][j] * vector[j]
        
output

array([[ 95.],
       [230.],
       [365.]])

In [46]:
#########################################
# Outputting Manually Calculated Vector #
#########################################

np.savetxt('output_forloop.csv', output)

In [47]:
###########################
# Numpy-Based Calculation #
###########################

output_2 = np.dot(matrix, vector)

output_2

array([[ 95.],
       [230.],
       [365.]])

In [48]:
######################################
# Outputting Numpy-Based Calculation #
######################################

np.save('output_dot.npy', output_2)

In [49]:
#########################
# Outputting Difference #
#########################

np.savetxt('output_difference.csv', output_2 - output)